config/routes.rb
Rails.application.routes.draw do
  resources :diagnostics
  resources :medical_reports
  resources :rooms
  resources :payments
  resources :medications
  resources :prescriptions
  resources :specialities
  resources :appointments
  resources :doctors
  resources :patients
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor
	belongs_to :patient
	has_one :prescription
	has_one :payment
	has_one :diagnostic, dependent: :destroy
end

app/models/diagnostic.rb
class Diagnostic < ApplicationRecord
	belongs_to :appointment
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	belongs_to :user
	belongs_to :speciality
	has_many :appointments
	has_many :prescriptions
end

app/models/medical_report.rb
class MedicalReport < ApplicationRecord
	belongs_to :patient
end

app/models/medication.rb
class Medication < ApplicationRecord
	belongs_to :prescription
end

app/models/patient.rb
class Patient < ApplicationRecord
	belongs_to :user
	has_many :appointments
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to:appointment
end

app/models/prescription.rb
class Prescription < ApplicationRecord
	belongs_to :appointment
	has_many :medications
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :appointments
end

app/models/speciality.rb
class Speciality < ApplicationRecord
	has_many :doctors
end

app/models/user.rb
class User < ApplicationRecord
	has_one :patient
	has_one :doctor
end

app/controllers/medical_reports_controller.rb
class MedicalReportsController < InheritedResources::Base

  private

    def medical_report_params
      params.require(:medical_report).permit(:patient_id, :description, :date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/medical_reports_helper.rb
module MedicalReportsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/medical_reports/_form.html.erb
<%= form_with(model: medical_report) do |form| %>
  <% if medical_report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medical_report.errors.count, "error") %> prohibited this medical_report from being saved:</h2>

      <ul>
        <% medical_report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.text_field :patient_id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medical_reports/_medical_report.html.erb
<div id="<%= dom_id medical_report %>">
  <p>
    <strong>Patient:</strong>
    <%= medical_report.patient_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= medical_report.description %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= medical_report.date %>
  </p>

</div>

app/views/medical_reports/edit.html.erb
<% content_for :title, "Editing medical report" %>

<h1>Editing medical report</h1>

<%= render "form", medical_report: @medical_report %>

<br>

<div>
  <%= link_to "Show this medical report", @medical_report %> |
  <%= link_to "Back to medical reports", medical_reports_path %>
</div>

app/views/medical_reports/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Medical reports" %>

<h1>Medical reports</h1>

<div id="medical_reports">
  <% @medical_reports.each do |medical_report| %>
    <%= render medical_report %>
    <p>
      <%= link_to "Show this medical report", medical_report %>
    </p>
  <% end %>
</div>

<%= link_to "New medical report", new_medical_report_path %>

app/views/medical_reports/new.html.erb
<% content_for :title, "New medical report" %>

<h1>New medical report</h1>

<%= render "form", medical_report: @medical_report %>

<br>

<div>
  <%= link_to "Back to medical reports", medical_reports_path %>
</div>

app/views/medical_reports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @medical_report %>

<div>
  <%= link_to "Edit this medical report", edit_medical_report_path(@medical_report) %> |
  <%= link_to "Back to medical reports", medical_reports_path %>

  <%= button_to "Destroy this medical report", @medical_report, method: :delete %>
</div>