config/routes.rb
Rails.application.routes.draw do
  resources :diagnostics
  resources :medical_reports
  resources :rooms
  resources :payments
  resources :medications
  resources :prescriptions
  resources :specialities
  resources :appointments
  resources :doctors
  resources :patients
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor
	belongs_to :patient
	has_one :prescription
	has_one :payment
	has_one :diagnostic, dependent: :destroy
end

app/models/diagnostic.rb
class Diagnostic < ApplicationRecord
	belongs_to :appointment
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	belongs_to :user
	belongs_to :speciality
	has_many :appointments
	has_many :prescriptions
end

app/models/medical_report.rb
class MedicalReport < ApplicationRecord
	belongs_to :patient
end

app/models/medication.rb
class Medication < ApplicationRecord
	belongs_to :prescription
end

app/models/patient.rb
class Patient < ApplicationRecord
	belongs_to :user
	has_many :appointments
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to:appointment
end

app/models/prescription.rb
class Prescription < ApplicationRecord
	belongs_to :appointment
	has_many :medications
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :appointments
end

app/models/speciality.rb
class Speciality < ApplicationRecord
	has_many :doctors
end

app/models/user.rb
class User < ApplicationRecord
	has_one :patient
	has_one :doctor
end

app/controllers/payments_controller.rb
class PaymentsController < InheritedResources::Base

  private

    def payment_params
      params.require(:payment).permit(:appointment_id, :prix, :paiement_method)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :appointment_id, style: "display: block" %>
    <%= form.number_field :appointment_id %>
  </div>

  <div>
    <%= form.label :prix, style: "display: block" %>
    <%= form.number_field :prix %>
  </div>

  <div>
    <%= form.label :paiement_method, style: "display: block" %>
    <%= form.text_field :paiement_method %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Appointment:</strong>
    <%= payment.appointment_id %>
  </p>

  <p>
    <strong>Prix:</strong>
    <%= payment.prix %>
  </p>

  <p>
    <strong>Paiement method:</strong>
    <%= payment.paiement_method %>
  </p>

</div>

app/views/payments/edit.html.erb
<% content_for :title, "Editing payment" %>

<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Payments" %>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<% content_for :title, "New payment" %>

<h1>New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>