config/routes.rb
Rails.application.routes.draw do
  resources :diagnostics
  resources :medical_reports
  resources :rooms
  resources :payments
  resources :medications
  resources :prescriptions
  resources :specialities
  resources :appointments
  resources :doctors
  resources :patients
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor
	belongs_to :patient
	has_one :prescription
	has_one :payment
	has_one :diagnostic, dependent: :destroy
end

app/models/diagnostic.rb
class Diagnostic < ApplicationRecord
	belongs_to :appointment
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	belongs_to :user
	belongs_to :speciality
	has_many :appointments
	has_many :prescriptions
end

app/models/medical_report.rb
class MedicalReport < ApplicationRecord
	belongs_to :patient
end

app/models/medication.rb
class Medication < ApplicationRecord
	belongs_to :prescription
end

app/models/patient.rb
class Patient < ApplicationRecord
	belongs_to :user
	has_many :appointments
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to:appointment
end

app/models/prescription.rb
class Prescription < ApplicationRecord
	belongs_to :appointment
	has_many :medications
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :appointments
end

app/models/speciality.rb
class Speciality < ApplicationRecord
	has_many :doctors
end

app/models/user.rb
class User < ApplicationRecord
	has_one :patient
	has_one :doctor
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tache Finale" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if admin_user_signed_in? %>
      <h1>Welcome Home, <%= current_admin_user.email%></h1>
      <%= link_to'Sign out', destroy_admin_user_session_path, data: {method: :delete } %>
    <%else%>
    <h1>Home</h1>
      <%= link_to'Sign in', new_admin_user_session_path %>
    <%end%>
    <p>
  <td>
    <% if params[:controller] == "appointments" %>
    <%= link_to 'Appointments', appointments_path, class:"active"%>
    <%else %>
    <%= link_to 'Appointments', appointments_path, class:""%>
    <% end%>
  </td>
  <td>
    <%if params[:controller] == "diagnostics" %>
      <%= link_to 'Diagnostics', diagnostics_path, class:"active"%>
        <%else%>
      <%= link_to 'Diagnostics',diagnostics_path, class:""%>
    <%end%>
  </td>
  <td>
    <%if params[:controller] == "doctors" %>
      <%= link_to 'Doctors', doctors_path, class:"active"%>
        <%else%>
      <%= link_to 'Doctors', doctors_path, class:""%>
    <%end%>
  </td>
  <td>
    <% if params[:controller] == "medical_reports" %>
        <%= link_to 'Medical_reports', medical_reports_path, class:"active"%>
      <%else%>
        <%= link_to 'Medical_reports', medical_reports_path, class:""%>
    <%end%>
  </td>
  <td>
    <% if params[:controller] == "medications" %>
      <%= link_to 'Medications', medications_path, class:"active"%>
        <%else%>
      <%= link_to'Medications', medications_path, class:""%>
    <%end%>
  </td>
  <td>
    <% if params[:controller] == "patients" %>
       <%= link_to 'Patients', patients_path, class:"active"%>
      <%else%>
       <%= link_to'Patients', patients_path, class:""%>
    <%end%>
  </td>
  <td>
    <% if params[:controller] == "payments" %>
        <%= link_to 'Payments', payments_path, class:"active"%>
      <%else%>
        <%= link_to 'Payments', payments_path, class:""%>
    <%end%>
  </td>
  <td>
    <% if params[:controller] == "prescriptions" %>
       <%= link_to 'Prescriptions', prescriptions_path, class:"active"%>
      <%else%>
       <%= link_to 'Prescriptions', prescriptions_path, class:""%>
    <%end%>
  </td>
  <td>
    <% if params[:controller] == "users" %>
       <%= link_to 'Users', users_path, class:"active"%>
      <%else%>
       <%= link_to 'Users',users_path, class:""%>
    <%end%>
  </td>
  <td>
    <% if params[:controller] == "rooms" %>
       <%= link_to 'Rooms', rooms_path, class:"active"%>
      <%else%>
       <%= link_to 'Rooms', rooms_path, class:""%>
    <%end%>
  </td>
  <td>
    <% if params[:controller] == "specialities" %>
       <%= link_to 'Specialities', specialities_path, class:"active"%>
      <%else%>
       <%= link_to 'Specialities',specialities_path, class:""%>
    <%end%>
  </td>
</p>
    <%= yield %>
  </body>
</html>